version: "3"
services:
  discord-bot:
    build: .
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    networks:
      - coolify
networks:
  coolify:
    external: true
